### ISSUE TITLE
STI College

### ISSUE THREAD

**Issue by dengbalaga** [twbs/bootstrap-expo#1619] opened 2015-03-24 02:44 UTC
Hi, i would like to submit our site http://www.sti.edu.

Company: STI College
Developer/Designer: Dennis Balaga

Description of Site:
One of the largest networks of schools in the Philippines. With its unique Enrollment to Employment System (E2E), STI continues to nurture globally competitive graduates in the fields of Information and Communications Technology, Tourism and Hospitality Management, Business and Management, Engineering, Arts and Sciences, and Healthcare

![stiedu-printcreen3](https://cloud.githubusercontent.com/assets/10105074/6794850/aa6a1bb4-d212-11e4-8e86-becc097251a1.jpg)
![stiedu-printcreen2](https://cloud.githubusercontent.com/assets/10105074/6794851/af8353b8-d212-11e4-9f59-480eac61844f.jpg)

**Comment by mdo** [comment] 2015-03-30 19:09
Dupe of another issue.

**Closed by mdo** 2015-03-30 19:09 UTC
